version: "3"
networks:
  default:
    name: Selenium-Grid-4
services:
  node-chrome:
    image: selenium/node-chrome:__CHROME-NODE-TAG__
    container_name: Node-Chrome-__CHROME-NODE-TAG__
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=32
    volumes:
      - /home/runner/work/shadowroot-digger-java/:/home/runner/work/shadowroot-digger-java
    ports:
      - "5900:5900"

  selenium-hub:
    image: selenium/hub:__SELENIUM-HUB-TAG__
    container_name: Selenium-Hub-__SELENIUM-HUB-TAG__
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"