#CI/MANUAL TRIGGER
name: Build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java-version: [ '8' ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: '${{ java-version }}'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Test with Maven
        if: ${{ matrix.java-version == '8' }}
        run: mvn test
        