#CI/MANUAL TRIGGER
name: Build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2019, ubuntu-20.04, macOS-11 ]
        java-version: [ '8', '11', '17' ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: '${{ matrix.java-version }}'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots compile -DskipTests=true

      - name: Test with Maven
        if: ${{ matrix.os == 'windows-2019' && matrix.java-version == '8' }}
        run: mvn test
