name: Publish Maven Package

env:
    MAVEN_PACKAGE_VERSION: "1.0.0-SNAPSHOT"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java-version: [ '8' ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Up Maven Central - JAVA ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: '${{ matrix.java-version }}'
          distribution: 'temurin'
          server-id: ${{ secrets.OSSRH_ID }}
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_TOKEN }}
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          settings-path: ${{ github.workspace }}

      - name: Find And Replace Values (settings.xml)
        uses: datamonsters/replace-action@v2
        with:
          files: settings.xml
          replacements: '__SERVERID__=${{ secrets.OSSRH_ID }},__USERNAME__=${{ secrets.OSSRH_USERNAME }},__PASSWORD__=${{ secrets.OSSRH_TOKEN }},__PROFILEID__=${{ secrets.OSSRH_ID }},__PASSPHRASE__=${{ secrets.MAVEN_GPG_PASSPHRASE }}'

      - name: Build with Maven - JAVA ${{ matrix.java-version }}
        run: mvn -B package -DskipTests=true --file pom.xml

      - name: Publish Maven Package - JAVA ${{ matrix.java-version }}
        run: mvn -B deploy -DskipTests=true -s settings.xml
