name: Publish Maven Package

env:
    MAVEN_PACKAGE_VERSION: "1.0.0-SNAPSHOT"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java-version: [ '8' ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Find And Replace Values (settings.xml)
        uses: datamonsters/replace-action@v2
        with:
          files: settings.xml
          replacements: '__SERVERID__=${{ secrets.OSSRH_ID }},__USERNAME__=${{ secrets.OSSRH_USERNAME }},__PASSWORD__=${{ secrets.OSSRH_TOKEN }},__PASSSPHRASE__=${{ secrets.MAVEN_GPG_PASSPHRASE }}'

      - name: Set Up Maven Central - JAVA ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: '${{ matrix.java-version }}'
          distribution: 'temurin'
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        run: mvn -B package -DskipTests=true --file pom.xml

      - name: Publish Maven Package
        run: mvn -B deploy -DskipTests=true -s settings.xml
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
